### ISSUE TITLE
Import scripts for The Icelandic Gigaword Corpus

### ISSUE THREAD

**Issue by egillanton** [cadia-lvl/ictk#1]
- [x] Get all extracted text from IGC
- [ ] Get extracted text from IGC from specific folder such as news articles
- [ ] Update the descriptive argparser /  [click](https://click.palletsprojects.com/)

**Comment by HaukurPall** [comment]
Can we close this issue? I think all functionality is there.

**Comment by HaukurPall** [comment]
This has been implemented. We only extract the word-forms this time.
